apiVersion: v1
kind: Namespace
metadata:
    name: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
    namespace: frontend
spec:
    replicas: 3
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: TMorais9/soundcircle-frontend:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 3000
                  resources:
                      requests:
                          memory: "512Mi"
                          cpu: "250m"
                      limits:
                          memory: "1Gi"
                          cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
    name: frontend
    namespace: frontend
spec:
    selector:
        app: frontend
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
          nodePort: 31000
    type: NodePort

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: frontend-hpa
    namespace: frontend
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: frontend
    minReplicas: 2
    maxReplicas: 5
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 50