apiVersion: v1
kind: Namespace
metadata:
    name: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
    namespace: backend
    labels:
        app: backend
spec:
    replicas: 3
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: backend
                  image: tmorais04/soundcircle-backend:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 3000
                  envFrom:
                      - secretRef:
                            name: backend-secret
                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "200m"
                      limits:
                          memory: "512Mi"
                          cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
    name: backend
    namespace: backend
spec:
    selector:
        app: backend
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
    type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: backend-hpa
    namespace: backend
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: backend
    minReplicas: 2
    maxReplicas: 5
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 50

---
apiVersion: v1
kind: Secret
metadata:
    name: backend-secret
    namespace: backend
type: Opaque